var strict = require("./strict");

module.exports = {
  "extends": require.resolve("./strict.js"),
  "rules": {
    "arrow-body-style": 0,
    "consistent-return": 0,
    "func-names": 0,
    "import/no-named-as-default": 0,
    "max-len": 0,
    "new-cap": 0,
    "no-case-declarations": 0,
    "no-confusing-arrow": 0,
    "no-else-return": 0,
    "no-fallthrough": 0,
    "no-irregular-whitespace": 0,
    "no-param-reassign": 0,
    "no-return-assign": 0,
    "prefer-arrow-callback": 0,
    "prefer-template": 0,
    "quote-props": 0,
    "react/jsx-first-prop-new-line": 0,
    "react/jsx-key": 0,
    "react/jsx-no-bind": 0,
    "react/jsx-sort-prop-types": 0,
    "react/no-deprecated": 0,
    "react/prefer-es6-class": 0,
    "react/prefer-stateless-function": 0,
    "react/require-render-return": 0,
    "react/self-closing-comp": 0,
    "react/sort-comp": 0,
    "react/wrap-multilines": 0,

    "lodash/matches-prop-shorthand": 0,
    "lodash/matches-shorthand": 0,
    "lodash/path-style": 0,
    "lodash/prefer-chain": 0,
    "lodash/prefer-constant": 0,
    "lodash/prefer-includes": 0,
    "lodash/prefer-is-nil": 0,
    "lodash/prefer-lodash-chain": 0,
    "lodash/prefer-lodash-method": 0,
    "lodash/prefer-lodash-typecheck": 0,
    "lodash/prefer-map": 0,
    "lodash/prefer-noop": 0,
    "lodash/prefer-reject": 0,
    "lodash/prefer-startswith": 0,
    "lodash/prop-shorthand": 0,
  },
};
