#!/usr/bin/env node
var spawn = require('child_process').spawn;
var packageInfo = require('./package.json');

console.log("Installing peer dependencies");

var dependencies = [];

Object.keys(packageInfo.devDependencies)
  .forEach(function(dependency) {
    dependencies.push(dependency + "@" + packageInfo.devDependencies[dependency])
  });

var install = spawn('npm', [
  'install',
  '--save-dev',
].concat(dependencies));

install.stdout.on('data', (data) => console.log(data.toString()));
install.stderr.on('data', (data) => console.error(data.toString()));

install.on('close', (code) => {
  if (code === 0) {
    console.log(`install was successful`);
  } else {
    console.log(`install failed with exit code ${code}`);
  }
});
