#!/usr/bin/env node
var spawn = require('child_process').spawn;

console.log("Installing peer dependencies");

var install = spawn('npm', [
  'install',
  '--save-dev',
  'eslint@^2.9.0',
  'eslint-plugin-jsx-a11y@^1.2.0',
  'eslint-plugin-import@^1.7.0',
  'eslint-plugin-react@^5.0.0'
]);

install.stdout.on('data', (data) => console.log(data.toString()));
install.stderr.on('data', (data) => console.error(data.toString()));

install.on('close', (code) => {
  if (code === 0) {
    console.log(`install was successful`);
  } else {
    console.log(`install failed with exit code ${code}`);
  }
});
